version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${FRONTEND_PORT}:3000
    volumes:
      - .:/app
      - /app
      - /app/node_modules